export const enum DatabaseConfig {
	Host = 'AKABANE_CONFIG_DATABASE_HOST',
	Name = 'AKABANE_CONFIG_DATABASE_NAME',
	Username = 'AKABANE_CONFIG_DATABASE_USERNAME',
	Password = 'AKABANE_CONFIG_DATABASE_PASSWORD',
	Database = 'AKABANE_CONFIG_DATABASE_DATABASE'
}
